### PR TITLE
support IPv6

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by jimfulton** [comment]
Thanks for doing this!

**Comment by jimfulton** [comment]
I'm going to add travis later before merging this.

**Comment by gotcha** [comment]
Travis is already on. And tests pass.

**Comment by gotcha** [comment]
@jimfulton I wonder if there is a need to expand tests to run under IPv6. Or if we trust underlying infrastructure.

**Comment by jimfulton** [comment]
Oops

**Comment by gotcha** [comment]
@jimfulton Would you mind giving me permission on PyPI to release ? (userid gotcha)

**Comment by jimfulton** [comment]
Released 2.1.0. Thanks again.

**Comment by jimfulton** [comment]
I also made you a pypi owner.

**Comment by gotcha** [comment]
Thanks

**Comment by jimfulton** [comment]
FWIW, I find parts of asyncio(/trollius) to be **very** similar to ngi.  Working on the networking for ZEO 5 was very similar to working with ngi.  I thought of making an asyncio backend for ngi, but decided it would be better, at least for new code, to just use asyncio.

**Pull request merged**
